### PR TITLE
Botplay consent [client-side]

### PR DESCRIPTION
**Pull request by xenkap**
because consent matters
[requires pulling https://github.com/Snirozu/Funkin-Online-Server/pull/3]

### CODE REVIEW

**Comment by xenkap** [comment]
shit

**Comment by xenkap** [comment]
image
maybe don't pull it yet (freeplay)

**Comment by xenkap** [comment]
i forgot to push the fix hold on

**Comment by Snirozu** [comment]
i would rather make botplay available when unlock gameplay modifiers option is enabled or when it's synced with the host rather than permitting specific players to enable it

my concept for botplay would be to just make it a gameplay modifier that when it's enabled FP gets disabled and the other player sees botplay text on the opposite side

**Comment by xenkap** [comment]
mk. ill keep this open but i'll probably make a pr with that if you don't

**Comment by Snirozu** [comment]
if you want to do that for me then go ahead

**Pull request closed without merging**
